services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./broker/config:/mosquitto/config:rw
    restart: unless-stopped
    networks:
      - vapi_net
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "health", "-m", "check"]
      interval: 2s
      timeout: 2s
      retries: 5
      
  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - GATEWAY_PORT=9010
      - MQTT_BROKER_HOST=mqtt
      - MQTT_BROKER_PORT=1883
    networks:
      - vapi_net
    depends_on:
      mqtt:
        condition: service_healthy
    tty: true
    stdin_open: true

  vapi1:
    build: ./vapi
    container_name: vapi1
    environment:
      - VEHICLE_ID=truck_1
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=9010
    depends_on:
      - gateway
    networks:
      - vapi_net

  vapi2:
    build: ./vapi
    container_name: vapi2
    environment:
      - VEHICLE_ID=truck_2
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=9010
    depends_on:
      - gateway
    networks:
      - vapi_net

  vapi3:
    build: ./vapi
    container_name: vapi3
    environment:
      - VEHICLE_ID=truck_3
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=9010
    depends_on:
      - gateway
    networks:
      - vapi_net
  
  mqtt_client:
    build: ./mqtt_client
    container_name: mqtt_client
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER_HOST=mqtt
      - MQTT_BROKER_PORT=1883
    networks:
      - vapi_net
    stdin_open: true
    tty: true

networks:
  vapi_net:
    driver: bridge
