version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - GATEWAY_PORT=9010
    networks:
      - vapi_net
    tty: true
    stdin_open: true

  vapi1:
    build: ./vapi
    container_name: vapi1
    environment:
      - VEHICLE_ID=truck_1
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=9010
    depends_on:
      - gateway
    networks:
      - vapi_net

  vapi2:
    build: ./vapi
    container_name: vapi2
    environment:
      - VEHICLE_ID=truck_2
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=9010
    depends_on:
      - gateway
    networks:
      - vapi_net

  vapi3:
    build: ./vapi
    container_name: vapi3
    environment:
      - VEHICLE_ID=truck_3
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=9010
    depends_on:
      - gateway
    networks:
      - vapi_net

networks:
  vapi_net:
    driver: bridge
